apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: staticsites.hosting.example.com
spec:
  group: hosting.example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - source
            properties:
              source:
                type: object
                required:
                - type
                properties:
                  type:
                    type: string
                    enum: ["git", "docker", "url"]
                  git:
                    type: object
                    properties:
                      repository:
                        type: string
                      branch:
                        type: string
                        default: "main"
                      path:
                        type: string
                        default: "."
                  docker:
                    type: object
                    properties:
                      image:
                        type: string
                      path:
                        type: string
                        default: "/app"
                  url:
                    type: object
                    properties:
                      archive:
                        type: string
              build:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: false
                  command:
                    type: string
                    default: "npm run build"
                  outputDir:
                    type: string
                    default: "dist"
              spa:
                type: boolean
                default: false
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Building", "Ready", "Failed"]
                default: "Pending"
              message:
                type: string
              url:
                type: string
              publishedAt:
                type: string
                format: date-time
              jobName:
                type: string
    additionalPrinterColumns:
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: URL
      type: string
      jsonPath: .status.url
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: staticsites
    singular: staticsite
    kind: StaticSite
    shortNames:
    - ss