apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: staticsites.hosting.example.com
spec:
  group: hosting.example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - source
            properties:
              source:
                type: object
                required:
                - type
                properties:
                  type:
                    type: string
                    enum: ["git", "docker", "url"]
                    description: "Source type for the static site"
                  git:
                    type: object
                    properties:
                      repository:
                        type: string
                        description: "Git repository URL"
                      branch:
                        type: string
                        default: "main"
                        description: "Git branch to build from"
                      path:
                        type: string
                        default: "."
                        description: "Path within repository to build"
                      secretRef:
                        type: object
                        properties:
                          name:
                            type: string
                            description: "Secret containing Git credentials"
                    description: "Git source configuration"
                  docker:
                    type: object
                    properties:
                      image:
                        type: string
                        description: "Docker image containing static files"
                      path:
                        type: string
                        default: "/app"
                        description: "Path within container containing static files"
                    description: "Docker source configuration"
                  url:
                    type: object
                    properties:
                      archive:
                        type: string
                        description: "URL to downloadable archive (zip/tar.gz)"
                      path:
                        type: string
                        default: "."
                        description: "Path within archive to extract"
                    description: "URL source configuration"
              build:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: false
                    description: "Enable build step (for frameworks like React, Vue, etc.)"
                  command:
                    type: string
                    default: "npm run build"
                    description: "Build command to execute"
                  outputDir:
                    type: string
                    default: "dist"
                    description: "Directory containing built files"
                  image:
                    type: string
                    default: "node:18-alpine"
                    description: "Build container image"
                description: "Build configuration for static site generators"
              domain:
                type: string
                description: "Custom domain (optional, defaults to <cr-name>.sites.apps.example.com)"
              spa:
                type: boolean
                default: false
                description: "Enable SPA mode (serve index.html on 404)"
              headers:
                type: object
                additionalProperties:
                  type: string
                description: "Custom HTTP headers to set"
          status:
            type: object
            properties:
              phase:
                type: string
                enum:
                - "Pending"
                - "Building"
                - "Uploading"
                - "Ready"
                - "Failed"
                - "Deleting"
                default: "Pending"
              message:
                type: string
                description: "Status message or error details"
              url:
                type: string
                description: "Public URL where the site is accessible"
              lastBuildTime:
                type: string
                format: date-time
              jobName:
                type: string
                description: "Name of the current/last build job"
              buildNumber:
                type: integer
                description: "Incremental build number"
    additionalPrinterColumns:
    - name: Phase
      type: string
      description: Current phase of the static site
      jsonPath: .status.phase
    - name: URL
      type: string
      description: Public URL of the site
      jsonPath: .status.url
    - name: Last Build
      type: date
      jsonPath: .status.lastBuildTime
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: staticsites
    singular: staticsite
    kind: StaticSite
    shortNames:
    - ss