---
# MinIO Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
# MinIO Secrets
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: minio
type: Opaque
data:
  # admin:password123 (base64 encoded)
  MINIO_ROOT_USER: YWRtaW4=
  MINIO_ROOT_PASSWORD: cGFzc3dvcmQxMjM=
---
# MinIO PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-storage
  namespace: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
# MinIO Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command:
        - /bin/bash
        - -c
        args:
        - minio server /data --console-address :9001
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_ROOT_PASSWORD
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        volumeMounts:
        - name: storage
          mountPath: /data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: minio-storage
---
# MinIO API Service
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
spec:
  selector:
    app: minio
  ports:
  - name: api
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: console
    port: 9001
    targetPort: 9001
    protocol: TCP
  type: ClusterIP
---
# MinIO Console Route (for admin access)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: minio-console
  namespace: minio
spec:
  host: minio-console.apps.example.com
  to:
    kind: Service
    name: minio
  port:
    targetPort: console
  tls:
    termination: edge
---
# MinIO Client Job (for initial setup)
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-setup
  namespace: minio
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mc
        image: quay.io/minio/mc:latest
        command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "Waiting for MinIO to be ready..."
          until mc alias set myminio http://minio.minio.svc:9000 admin password123; do
            echo "MinIO not ready, waiting..."
            sleep 5
          done
          
          echo "Creating sites bucket..."
          mc mb myminio/sites --ignore-existing
          
          echo "Setting public read policy for sites bucket..."
          mc anonymous set public myminio/sites
          
          echo "MinIO setup complete!"
        env:
        - name: MC_HOST_myminio
          value: "http://admin:password123@minio.minio.svc:9000"
      backoffLimit: 5