---
# ServiceAccount for build jobs
apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-site-builder
  namespace: static-hosting
---
# Role for build jobs (minimal permissions)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: static-site-builder
  namespace: static-hosting
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
---
# RoleBinding for build jobs
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: static-site-builder
  namespace: static-hosting
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: static-site-builder
subjects:
- kind: ServiceAccount
  name: static-site-builder
  namespace: static-hosting
---
# NetworkPolicy for static hosting (optional security)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: static-hosting-network-policy
  namespace: static-hosting
spec:
  podSelector:
    matchLabels:
      app: nginx-proxy
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: openshift-ingress
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: minio
    ports:
    - protocol: TCP
      port: 9000
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53